name: nlp-environment
channels:
  - conda-forge
dependencies:
  - pandas
  - urllib
  - os
  - numpy
  - re
  - matplotlib
  - collections
  - itertools
  - tqdm
  - nltk
  - bs4
  - scipy
  - sklearn
  - warnings
